#[cfg(feature = "ssr")]
pub mod admin;
pub mod assets;
#[cfg(feature = "ssr")]
pub mod auth;
#[cfg(feature = "ssr")]
pub mod document_upload;
pub mod errors;
#[cfg(feature = "ssr")]
pub mod feedback;
#[cfg(feature = "ssr")]
pub mod health;
pub mod ingest;
#[cfg(feature = "ssr")]
pub mod pat;
#[cfg(feature = "ssr")]
pub mod prompts;
#[cfg(feature = "ssr")]
pub mod rag;
pub mod releases;
pub mod schemas;
#[cfg(feature = "ssr")]
pub mod search;
#[cfg(feature = "ssr")]
pub mod sync;
#[cfg(feature = "ssr")]
pub mod token_validation;
#[cfg(feature = "ssr")]
pub mod upload;
