#!/bin/bash
# Setup script for local development environment
# This script starts Docker dependencies and creates a .env file with the correct credentials

set -e

echo "🚀 Setting up Lekton development environment..."
echo ""

# Check if docker-compose is available
if ! command -v docker-compose &> /dev/null; then
    echo "❌ docker-compose not found. Please install Docker and Docker Compose first."
    exit 1
fi

# Check if npm is available
if ! command -v npm &> /dev/null; then
    echo "❌ npm not found. Please install Node.js first."
    exit 1
fi

# Install Node.js dependencies (DaisyUI)
echo "📦 Installing Node.js dependencies (DaisyUI)..."
npm install

if [ $? -ne 0 ]; then
    echo "❌ Failed to install npm dependencies"
    exit 1
fi

echo "✅ Node.js dependencies installed"
echo ""

# Start dependencies
echo "📦 Starting MongoDB, Garage S3, and Meilisearch..."
docker-compose up -d mongodb garage meilisearch

echo "⏳ Waiting for services to be healthy..."
sleep 5

# Wait for garage to be healthy
max_attempts=30
attempt=0
while ! docker-compose ps garage | grep -q "healthy"; do
    attempt=$((attempt + 1))
    if [ $attempt -ge $max_attempts ]; then
        echo "❌ Timeout waiting for Garage to become healthy"
        exit 1
    fi
    echo "   Waiting for Garage... ($attempt/$max_attempts)"
    sleep 2
done

echo "✅ Garage is healthy"

# Wait for Meilisearch to be healthy
attempt=0
while ! docker-compose ps meilisearch | grep -q "healthy"; do
    attempt=$((attempt + 1))
    if [ $attempt -ge $max_attempts ]; then
        echo "❌ Timeout waiting for Meilisearch to become healthy"
        exit 1
    fi
    echo "   Waiting for Meilisearch... ($attempt/$max_attempts)"
    sleep 2
done

echo "✅ Meilisearch is healthy"

# Run garage-init to create bucket and keys
echo "🔧 Initializing Garage (creating bucket and API keys)..."
docker-compose up garage-init

# Extract credentials from logs
echo "📝 Extracting credentials..."
INIT_LOGS=$(docker-compose logs garage-init)

ACCESS_KEY=$(echo "$INIT_LOGS" | grep "Access Key ID:" | tail -1 | awk '{print $NF}')
SECRET_KEY=$(echo "$INIT_LOGS" | grep "Secret Access Key:" | tail -1 | awk '{print $NF}')

if [ -z "$ACCESS_KEY" ] || [ -z "$SECRET_KEY" ]; then
    echo "❌ Failed to extract credentials from garage-init logs"
    echo "   Please check the logs with: docker-compose logs garage-init"
    exit 1
fi

echo "✅ Credentials extracted"
echo "   Access Key ID: $ACCESS_KEY"
echo "   Secret Key: ${SECRET_KEY:0:20}..."

# Create .env file
echo "📄 Creating .env file..."
cat > .env <<EOF
# Lekton Environment Configuration
# Auto-generated by setup-dev-env.sh on $(date)

# MongoDB Configuration
MONGODB_URI=mongodb://localhost:27017
MONGODB_DATABASE=lekton

# S3 Storage Configuration
S3_BUCKET=lekton-docs
S3_ENDPOINT=http://localhost:3900
AWS_ACCESS_KEY_ID=$ACCESS_KEY
AWS_SECRET_ACCESS_KEY=$SECRET_KEY
AWS_REGION=garage

# Service Token for API ingestion
SERVICE_TOKEN=demo-ingest-token

# Meilisearch Configuration
MEILISEARCH_URL=http://localhost:7700
MEILISEARCH_API_KEY=dev-master-key-change-in-prod

# Enable demo auth mode (bypasses OIDC)
DEMO_MODE=true

# Logging
RUST_LOG=lekton=info,tower_http=info

# Leptos configuration
LEPTOS_SITE_ADDR=127.0.0.1:3000
EOF

echo "✅ .env file created"
echo ""
echo "🎉 Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Run the application:"
echo "     cargo leptos watch"
echo ""
echo "  2. Or with dotenv-cli:"
echo "     dotenv cargo leptos watch"
echo ""
echo "  3. Open http://127.0.0.1:3000 in your browser"
echo ""
echo "To stop dependencies later:"
echo "  docker-compose down"
echo ""
