export const content = {
  en: {
    title: 'Lekton — documentation from your repositories',
    description: 'A self-hosted developer portal for Markdown, API schemas and reusable prompts. Sync content from CI, with access controls in the portal.',
    skip: 'Skip to content', navigation: 'Main navigation', language: 'Language', theme: 'Change theme',
    themeSystem: 'System theme (switch to light)', themeLight: 'Light theme (switch to dark)', themeDark: 'Dark theme (switch to system)',
    product: 'Product', setup: 'Setup', source: 'Source',
    headingFirst: 'Documentation,', headingSecond: 'from your repositories.',
    run: 'Run locally', setupHeading: 'Run it locally', readSource: 'Read the source',
    previewLabel: 'Illustrative portal interface', previewSearch: 'Search documentation…',
    platform: 'Platform', gettingStarted: 'Getting started', deployment: 'Deployment guide', architecture: 'Architecture',
    schemas: 'Schemas', billing: 'Billing API', prompts: 'Prompts', review: 'Code review',
    deploymentCopy: 'Build the service image, apply the configuration and verify the deployment.',
    related: 'Related', reviewPrompt: 'Code review prompt',
    previewCaption: 'Illustrative interface · search requires Meilisearch',
    repositories: 'Your repositories', repositoryFiles: 'Markdown · schemas · prompts',
    workflowCopy: 'Run the sync command in CI to publish changed content.',
    workflowHint: 'See a sync example', workflowDescription: 'Give your Markdown files YAML front matter. Configure a service token and a portal URL, then run lekton-sync from your pipeline. It compares content hashes and uploads changes.',
    workflowDocs: 'Read the CLI guide',
    included: 'What is included', docsTitle: 'Documentation and editing',
    docsBody: 'Sync Markdown from service repositories, or edit through the portal with the Markdown and visual editor. Organize documents into a hierarchy and validate internal links.',
    schemasTitle: 'OpenAPI, AsyncAPI and JSON Schema',
    schemasBody: 'Publish versioned API schemas alongside your documentation. Browse them through the registry and the corresponding schema viewers.',
    accessTitle: 'Access controls, prompts and MCP',
    accessBody: 'Control who can read and write content. Share versioned reusable prompts and expose documentation, schemas and prompts to MCP clients using Personal Access Tokens.',
    copy: 'Copy commands', copied: 'Copied', copyError: 'Copy failed. Select and copy the commands below.',
    startNote: 'Requires Git and Docker Compose. First run builds the application. Demo authentication is for local evaluation.',
    localLink: 'Open localhost:3000', demoLogin: 'Demo login: admin / admin',
    optionalNote: 'Search needs Meilisearch. RAG needs Qdrant, embeddings and an LLM provider.',
    requirementsTitle: 'What you need to run it',
    requirementsIntro: 'The portal stores metadata in MongoDB and content in S3-compatible storage. Enable the additional services you need.',
    coreTitle: 'Core portal', coreBody: 'MongoDB and S3-compatible storage. Docker Compose includes MongoDB, Garage, Meilisearch, Qdrant and example content.',
    searchTitle: 'Optional search', searchBody: 'Meilisearch and the search feature flag. Search is disabled by default; providing a service URL alone does not enable it.',
    ragTitle: 'Optional RAG', ragBody: 'Qdrant, an embedding provider, an LLM provider and the RAG feature flag. Retrieval quality depends on your content and configuration.',
    searchToggle: 'Enable search', ragToggle: 'Enable RAG',
    featureFlagIntro: 'Set feature flags on the Lekton server, in its environment or configuration file, together with the required service URLs and credentials. Compose does not forward arbitrary host variables.',
    configLink: 'Configuration reference', ragLink: 'RAG setup',
    productionTitle: 'Before production',
    productionBody: 'Configure a real OIDC or OAuth2 provider, replace demo credentials and service tokens, and configure persistent storage. The Compose example is a local evaluation environment.',
    productionLink: 'Read the operations guide',
    closeTitle: 'Start with your own documentation.',
    closeBody: 'Try the local instance, sync a small repository, and see how the portal fits your team’s workflow.',
    releases: 'Download a release', documentation: 'Documentation', license: 'AGPL-3.0',
    footerCopy: 'Open source. Self-hosted. Built in Rust.',
  },
  it: {
    title: 'Lekton — documentazione dai tuoi repository',
    description: 'Un portale per sviluppatori da ospitare sulla tua infrastruttura: Markdown, schemi API e prompt riutilizzabili. Sincronizza i contenuti dalla CI e gestisci gli accessi nel portale.',
    skip: 'Vai al contenuto', navigation: 'Navigazione principale', language: 'Lingua', theme: 'Cambia tema',
    themeSystem: 'Tema di sistema (passa al chiaro)', themeLight: 'Tema chiaro (passa allo scuro)', themeDark: 'Tema scuro (passa al sistema)',
    product: 'Prodotto', setup: 'Avvio', source: 'Codice',
    headingFirst: 'La documentazione,', headingSecond: 'dai tuoi repository.',
    run: 'Avvia in locale', setupHeading: 'Avvia in locale', readSource: 'Esplora il codice',
    previewLabel: 'Esempio illustrativo dell’interfaccia del portale', previewSearch: 'Cerca nella documentazione…',
    platform: 'Piattaforma', gettingStarted: 'Primi passi', deployment: 'Guida al deployment', architecture: 'Architettura',
    schemas: 'Schemi', billing: 'API di fatturazione', prompts: 'Prompt', review: 'Revisione del codice',
    deploymentCopy: 'Crea l’immagine del servizio, applica la configurazione e verifica il deployment.',
    related: 'Correlati', reviewPrompt: 'Prompt di revisione del codice',
    previewCaption: 'Interfaccia illustrativa · la ricerca richiede Meilisearch',
    repositories: 'I tuoi repository', repositoryFiles: 'Markdown · schemi · prompt',
    workflowCopy: 'Esegui il comando di sync nella CI per pubblicare i contenuti modificati.',
    workflowHint: 'Mostra un esempio di sync', workflowDescription: 'Aggiungi un front matter YAML ai file Markdown. Configura un token di servizio e l’URL del portale, quindi esegui lekton-sync nella pipeline. Confronta gli hash dei contenuti e carica le modifiche.',
    workflowDocs: 'Leggi la guida della CLI',
    included: 'Cosa include', docsTitle: 'Documentazione ed editor',
    docsBody: 'Sincronizza il Markdown dai repository dei servizi oppure modifica i contenuti dal portale, con l’editor Markdown e visuale. Organizza i documenti in una gerarchia e valida i link interni.',
    schemasTitle: 'OpenAPI, AsyncAPI e JSON Schema',
    schemasBody: 'Pubblica schemi API versionati insieme alla documentazione. Esplorali nel registro e nei visualizzatori dedicati ai diversi formati.',
    accessTitle: 'Controlli di accesso, prompt e MCP',
    accessBody: 'Gestisci chi può leggere e modificare i contenuti. Condividi prompt riutilizzabili e versionati e rendi disponibili documentazione, schemi e prompt ai client MCP tramite Personal Access Token.',
    copy: 'Copia i comandi', copied: 'Copiato', copyError: 'Copia non riuscita. Seleziona e copia i comandi qui sotto.',
    startNote: 'Servono Git e Docker Compose. Il primo avvio compila l’applicazione. L’autenticazione demo serve per la valutazione in locale.',
    localLink: 'Apri localhost:3000', demoLogin: 'Accesso demo: admin / admin',
    optionalNote: 'La ricerca richiede Meilisearch. Il RAG richiede Qdrant, un provider di embedding e un provider LLM.',
    requirementsTitle: 'Cosa serve per eseguirlo',
    requirementsIntro: 'Il portale conserva i metadati in MongoDB e i contenuti in uno storage compatibile con S3. Abilita i servizi aggiuntivi che ti servono.',
    coreTitle: 'Portale di base', coreBody: 'MongoDB e storage compatibile con S3. Docker Compose include MongoDB, Garage, Meilisearch, Qdrant e contenuti di esempio.',
    searchTitle: 'Ricerca opzionale', searchBody: 'Meilisearch e il flag della funzionalità di ricerca. La ricerca è disabilitata di default: configurare soltanto l’URL del servizio non la abilita.',
    ragTitle: 'RAG opzionale', ragBody: 'Qdrant, un provider di embedding, un provider LLM e il flag della funzionalità RAG. La qualità del recupero dipende dai contenuti e dalla configurazione.',
    searchToggle: 'Abilita la ricerca', ragToggle: 'Abilita il RAG',
    featureFlagIntro: 'Imposta i flag sul server Lekton, nell’ambiente o nel file di configurazione, insieme agli URL e alle credenziali dei servizi richiesti. Compose non inoltra automaticamente le variabili dell’host.',
    configLink: 'Guida alla configurazione', ragLink: 'Configurazione RAG',
    productionTitle: 'Prima della produzione',
    productionBody: 'Configura un provider OIDC o OAuth2 reale, sostituisci le credenziali demo e i token di servizio e configura storage persistente. L’esempio Compose è un ambiente di valutazione locale.',
    productionLink: 'Leggi la guida operativa',
    closeTitle: 'Parti dalla tua documentazione.',
    closeBody: 'Prova l’istanza locale, sincronizza un piccolo repository e valuta come il portale si inserisce nel lavoro del tuo team.',
    releases: 'Scarica una release', documentation: 'Documentazione', license: 'AGPL-3.0',
    footerCopy: 'Open source. Sulla tua infrastruttura. Sviluppato in Rust.',
  },
};
