name: Code Quality

on:
  push:
    branches: [main, "feat/*", "feature/*"]
  pull_request:
    branches: [main]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Check Rust formatting
        run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - name: Clippy (SSR)
        run: cargo clippy --features ssr --lib -- -D warnings

      - name: Clippy (hydrate)
        run: cargo clippy --features hydrate --lib -- -D warnings
