name: Code Quality

on:
  push:
    branches: [main, "feat/*", "feature/*"]
  pull_request:
    branches: [main]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Rust toolchain
        run: rustup toolchain install && rustup component add rustfmt

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - name: Check Rust formatting
        run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install Rust toolchain
        run: rustup toolchain install && rustup component add clippy

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 22
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Clippy (SSR)
        run: cargo clippy --features ssr --lib -- -D warnings

      - name: Clippy (hydrate)
        run: cargo clippy --features hydrate --lib -- -D warnings
